# Generated by Django 6.0 on 2025-12-08 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albnd', '0004_post_avaliacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='avaliacao',
        ),
        migrations.AddField(
            model_name='post',
            name='avaliacao_1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='avaliacao_2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='avaliacao_3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
