# Generated by Django 6.0 on 2025-12-08 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albnd', '0006_post_avaliacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='artista',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
